### ISSUE TITLE
Add `archivist install` command

### ISSUE THREAD

**Issue by nikhita** [openshift/online-archivist#15]
I'm trying to build something similar to online-archivist for https://openshift.io/. It would super cool to install archivist through just a command (similar to `ark install`, https://github.com/heptio/ark/issues/52).

We can have the user fill in the necessary options at the beginning. The docs are great for understanding what's going on step-by-step but it takes a lot of copy-pasting to get a working install going. xref #13 

Thoughts on this?

/cc @dgoodwin @vero-tess @damemi 
(cc'ing you all here because you have contributed to this repo, not sure who maintains it now :smile:)

**Comment by dgoodwin** [comment]
Sadly I believe nobody maintains now. :) Seems like a good idea though, would it have an operator? (ark as well?)

**Comment by nikhita** [comment]
> would it have an operator? (ark as well?)

maybe :)

ark is modelled as an operator, I think archivist could be modelled so as well.
